---
name: 'create release branch'
run-name: Creating release branch by ${{ github.actor }}
on:
  workflow_dispatch:

jobs:
  branch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    steps:
      - uses: actions/checkout@v6
      - uses: oleksiyrudenko/gha-git-credentials@v2
        with:
          name: 'github $GITHUB_ACTOR'
          email: 'github@mmprogrami.nl'
          token: '${{ secrets.GITHUB_TOKEN  }}'
      - name: Release branch with Maven
        run: |
          VERSION=`mvn -ntp help:evaluate -Dexpression=project.version -q -DforceStdout`
          RELEASE_VERSION=`echo $VERSION | sed -r 's/-SNAPSHOT/.0-SNAPSHOT/'`
          DEVELOPMENT_VERSION=`echo $VERSION | gawk 'match($1, /([0-9]+)\.([0-9]+)([\.-])(.*)/, a) {print a[1]"."(a[2]+1)a[3]a[4]}'`
          echo Updating version ${VERSION} to ${RELEASE_VERSION}. New development version: ${DEVELOPMENT_VERSION}
          mvn  -ntp -DupdateBranchVersions=true -DreleaseVersion=${RELEASE_VERSION} -DdevelopmentVersion=${DEVELOPMENT_VERSION} release:branch

